name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - name: Vue to Github Pages(with router)
        uses: undownding/VuePagesAction@1.0.3
        with:
          # Your username
          username: 'tonussi'
          # Your reponame
          reponame: 'menstrualconnect-page'
          # Your Github token
          token: ${{ secrets.ACTIONS_TOKEN }}
