name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - name: Vue to Github Pages(with router)
        uses: undownding/VuePagesAction@1.0.3
        with:
          username: 'tonussi'
          reponame: 'menstrualconnect-page'
          token: ${{ secrets.ACTIONS_TOKEN }}
          gitemail: lptonussi@gmail.com
          gitname: Lucas Tonussi
          gitmsg: Deploy
          cname: menstrual.com.br
